stages:
  - Services Tests Iterasys
  - Acceptance Tests Frontend Iterasys
  - Acceptance Tests Frontend Iterasys II
  - Acceptance Tests Mobile Iterasys

#######################################################################################################################################
####################################### API ###########################################################################################
#######################################################################################################################################
# API Testes com Docker+Pipeline LOGIN, BUSCA E ADIÇÃO
Testes Web com Docker+Pipeline LOGIN, BUSCA E ADIÇÃO:
    stage: Services Tests Iterasys
    image: "registry.gitlab.com/andrehz/dockerfastshopqa:latest"
    tags:
        - docker
    artifacts:
        when: on_failure 
        paths:
            - ./results
        expire_in: 1 week
    script:
        - robot -d ./results -v BROWSER:headlesschrome ./tests/api/LoginEBuscaEAdicaoPetz.robot  



#######################################################################################################################################
####################################### NAVEGAÇÃO #####################################################################################
#######################################################################################################################################
# WEB Testes com Docker+Pipeline LISTA DE LIVROS
Testes Web com Docker+Pipeline LISTA DE LIVROS:
    stage: Acceptance Tests Frontend Iterasys
    image: "registry.gitlab.com/andrehz/dockerfastshopqa:latest"
    tags:
        - docker
    artifacts:
        when: on_failure 
        paths:
            - ./results
        expire_in: 1 week
    script:
        - robot -d ./results -v BROWSER:headlesschrome ./tests/web/frontend/CriarListaDeLivros.robot


# WEB Testes com Docker+Pipeline MEUS LIVROS
Testes Web com Docker+Pipeline MEUS LIVROS:
    stage: Acceptance Tests Frontend Iterasys II
    image: "registry.gitlab.com/andrehz/dockerfastshopqa:latest"
    tags:
        - docker
    artifacts:
        when: on_failure 
        paths:
            - ./results
        expire_in: 1 week
    script:
        - robot -d ./results -v BROWSER:headlesschrome ./tests/web/frontend/CriarListaMeusLivros.robot
#######################################################################################################################################
####################################### MOBILE ########################################################################################
#######################################################################################################################################
# MOBILE Testes com Docker+Pipeline BUSCA VEICULOS
Testes Web com Docker+Pipeline BUSCA VEICULOS:
    stage: Acceptance Tests Mobile Iterasys
    image: "registry.gitlab.com/andrehz/dockerfastshopqa:latest"
    tags:
        - docker
    artifacts:
        when: on_failure 
        paths:
            - ./results
        expire_in: 1 week
    script:
        - robot -d ./results -v BROWSER:headlesschrome ./tests/mobile/frontend/Busca_Veiculo_Usado.robot